import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Libre_Franklin } from 'next/font/google';
import { Judson } from 'next/font/google';

const libre_franklin = Libre_Franklin({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-libre_franklin',
});
const judson = Judson({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-judson',
  weight: '400',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={libre_franklin.variable + ' ' + judson.variable}>{children}</body>
    </html>
  );
}
